import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSET_ROOT = ROOT / "assets" / "schedule-layers-v2"
OUTPUT = ROOT / "src" / "schedule-layer-manifests.js"

specs = {}
for manifest_path in sorted(ASSET_ROOT.glob("*/manifest.json")):
    spec = json.loads(manifest_path.read_text(encoding="utf-8"))
    specs[spec["activityId"]] = spec

payload = json.dumps(specs, ensure_ascii=False, separators=(",", ":"))
OUTPUT.write_text(
    "// Generated by tools/build_schedule_layer_manifest_bundle.py\n"
    f"window.SCHEDULE_LAYER_V2_SPECS={payload};\n",
    encoding="utf-8",
)
print(f"wrote {OUTPUT} ({len(specs)} manifests)")
