import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const app=readFileSync(path.join(root,'src/app.js'),'utf8');
const manifests=readFileSync(path.join(root,'src/schedule-layer-manifests.js'),'utf8');
const css=readFileSync(path.join(root,'src/schedule.css'),'utf8');
assert.ok(app.includes("function scheduleFramePath(file){return \`../assets/characters/seonhwa/schedule-actions/v2/\${file}\`;"),'일정 선화는 승인된 v2 낮은 한쪽 땋은 머리 프레임 경로만 사용해야 합니다.');
assert.ok(!/schedule-actions\/(?!v2\/)/.test(app),'실행 코드에 올림머리 구형 일정 프레임 경로가 남아 있으면 안 됩니다.');
assert.ok(!/schedule-actions\/(?!v2\/)/.test(manifests),'일정 매니페스트에 올림머리 구형 프레임 경로가 남아 있으면 안 됩니다.');
assert.match(css,/#activityStage\.schedule-layered \.stage-character\.pixel-sprite\{width:96px!important;height:96px!important/,'선화 쯔꾸르 표시 상자는 일정마다 동일한 96px이어야 합니다.');
assert.match(css,/#activityStage\.schedule-layered \.schedule-scene-layer\.layer-npc\{width:96px!important;height:96px!important/,'NPC 쯔꾸르 표시 상자도 선화와 동일한 96px이어야 합니다.');
console.log('PASS: all schedule heroes use approved low-side-braid v2 frames');
console.log('PASS: schedule Seonhwa and NPCs share the same 96px tukkur box and floor baseline');
