import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..');
const app=fs.readFileSync(path.join(root,'src/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'src/schedule.css'),'utf8');
const html=fs.readFileSync(path.join(root,'src/index.html'),'utf8');
const pngSize=file=>{const data=fs.readFileSync(file);return {width:data.readUInt32BE(16),height:data.readUInt32BE(20)};};
const shownVersion=html.match(/loading-version[^>]*>v([^<]+)/)?.[1];
for(const asset of ['app.js','style.css','schedule.css'])assert.ok(shownVersion&&html.includes(`${asset}?v=${shownVersion}`),`${asset} cache key`);
const contestantBlock=app.match(/const moonlightContestants=\[([\s\S]*?)\n\];/)?.[1]||'';
assert.equal((contestantBlock.match(/scores:\[/g)||[]).length,7,'선화 포함 참가자 8명');
const beats=app.match(/const moonlightStoryBeats=\[([\s\S]*?)\n\];/)?.[1]||'';
assert.equal((beats.match(/'[^']+'/g)||[]).length,8,'사용자가 확정한 8단계');
for(const phrase of ['신수와 선화','무대 중앙','팔과 손목, 손끝','왕과 심사관','여덟 참가자','상을 수여','반실사','능력치와 보상'])assert.ok(beats.includes(phrase),phrase);
assert.match(app,/moonlightMotionNames=\['opening-dialogue','stage-enter','dance','royal-judging','ranking','award','winner-acceptance','guardian-congratulation'\]/,'8단계 모션 순서');
assert.match(app,/opening\?moonlightOpeningDialogue\(session,0\):entrance\?moonlightOpeningDialogue\(session,1\)/,'신수 응원 뒤 선화 대답을 한 장면씩 교대 렌더링');
assert.doesNotMatch(app,/moonlightPreparationDialogue/,'신수와 선화를 한 장면에 함께 노출하지 않음');
assert.match(app,/age-\$\{dialogueAge\}-\$\{canonical\}-lowbraid-dialogue-v1\.png/,'연령별 대화 선화는 상태별 낮은 한쪽 땋은머리 초상 사용');
for(const expression of ['joyful','nervous','sad','determined','startled'])assert.ok(fs.existsSync(new URL(`../assets/characters/seonhwa/dialogue/age-09-${expression}-lowbraid-dialogue-v1.png`,import.meta.url)),`9세 ${expression} 낮은 땋은머리 대화 초상이 필요합니다.`);
for(const expression of ['joyful','nervous','sad','determined','startled'])assert.ok(fs.existsSync(new URL(`../assets/characters/seonhwa/dialogue/age-13-${expression}-lowbraid-dialogue-v1.png`,import.meta.url)),`13세 ${expression} 낮은 땋은머리 대화 초상이 필요합니다.`);
assert.match(app,/'13':\['joyful','nervous','sad','determined','startled'\]/,'13세의 모든 상태 대답은 전신 폴백으로 빠지면 안 됩니다.');
assert.match(app,/if\(qaCondition==='angry'\)game\.stress=55/,'분노 상태의 한가위 QA 화면을 직접 검수할 수 있어야 합니다.');
for(const file of fs.readdirSync(path.join(root,'assets/characters/seonhwa/dialogue')).filter(name=>name.endsWith('.png'))){const {width,height}=pngSize(path.join(root,'assets/characters/seonhwa/dialogue',file));assert.ok(height<=width*1.12,`${file}: 대화용 상반신 원화가 전신 비율로 남아 있으면 안 됩니다.`);}
assert.doesNotMatch(app,/dialogue-busts\/seonhwa/,'올림머리 대화 표정 세트를 더 이상 참조하지 않음');
assert.match(app,/const phrase=\[1,2,3,4,5,6,5,4,3,2\]/,'완성된 춤 프레임은 왕복 순서여야 합니다.');
assert.match(app,/Array\.from\(\{length:5\},\(\)=>phrase\)\.flat\(\)\.map\(frame\)/,'춤은 10fps·5초의 50프레임 계약이어야 합니다.');
assert.match(css,/moonlight-dance-50-frame 5s steps\(1,end\)/,'실제 프레임 춤은 5초 주기로 재생되어야 합니다.');
assert.match(css,/motion-dance \.pageant-hero-frames\.is-dance\{[^}]*bottom:19%!important[^}]*width:224px!important/,'춤은 무대 바닥선 위에서 조금 더 큰 크기로 보여야 합니다.');
assert.match(css,/pageant-hero-frames\.is-dance\{[^}]*left:50%!important/,'중앙 춤');
for(const age of ['09','13','16','19'])assert.ok(fs.existsSync(path.join(root,`assets/characters/seonhwa/identity-semi-real-v9/seonhwa-age${age}-identity-v9.png`)),`선화 ${age}세 반실사 기준 초상`);
assert.ok(fs.existsSync(path.join(root,'assets/events/holidays/moonlight-pageant/seonhwa/consistent-dance-v9/seonhwa-dance-slow-v1.png')),'complete dance');
assert.match(app,/const guardianType=game\.guardianType\|\|'hyeonmu';/,'신수 미선택 상태에도 도입 대화 유지');
assert.match(css,/motion-royal-judging \.festival-character-cut\.king-cut p[\s\S]*bottom:4%!important/,'왕의 얼굴과 대화창 분리');
assert.match(css,/speaker-seonhwa>\.sehwa-expression\{[^}]*width:100%!important[^}]*height:112%!important[^}]*background-position:center 64%!important[^}]*background-size:70% auto!important/,'선화 얼굴은 신수보다 크게 확대되면 안 됩니다.');
assert.match(app,/const portrait=playerWinner[\s\S]*baseSpriteForAge\(\)[\s\S]*moonlightEntrantImage\(winner\)/,'우승자별 나이 맞춤 반실사 수상 소감 분기');
assert.match(app,/festivalScoreboard\(session,'참가자 8명 최종 순위와 수상 결과'\)/,'8명 순위 발표');
assert.match(app,/festivalKingWinnerCongratulations\(session\)/,'왕 시상·축하');
assert.match(app,/festivalGuardianCut\(session\)/,'신수 마지막 축하');
console.log('PASS: 한가위 8단계, 동일 선화 중앙 전신 춤, 왕 시상, 우승자 반실사 소감, 신수 마무리');
