import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const block=(start,end)=>app.slice(app.indexOf(start),app.indexOf(end,app.indexOf(start)));
const ctx=vm.createContext({game:{age:13,currentDate:'2001-01-01',scheduleFormat:'phase-v1',dailySchedule:['herbs','reading','accounting'],sense:200,manners:200,dignity:200,charm:200,sensitivity:200,agility:200},canonicalizeChange:x=>x,actionUnlocked:()=>true,currentPhaseHoliday:()=>null,sehwaStandaloneQa:false,moonlightStandaloneQa:false,shuffled:x=>x,scheduleQaParams:new URLSearchParams()});
vm.runInContext(block('const actions = [','const activityRequirements='),ctx);
assert.equal(vm.runInContext("actions.filter(a=>a.retiredJob).length",ctx),0);
for(const id of ['errand','sweeping','herbs','houseclean','woodwork','loomwork','masonry','innhelp','ferryhelp','accounting'])assert.equal(vm.runInContext(`actions.some(a=>a.id==='${id}')`,ctx),false);
vm.runInContext(block('function normalizePhaseSchedule(){','function scheduleProjection(){'),ctx);
ctx.normalizePhaseSchedule();assert.equal(ctx.game.dailySchedule.join(','),'rest,reading,rest');
ctx.normalizePhaseSchedule();assert.equal(ctx.game.removedJobsMigrationV1.schedule.join(','),'herbs,reading,accounting');
vm.runInContext(block('const moonlightContestants=[','const moonlightStoryBeats='),ctx);
vm.runInContext(block('function moonlightAgeIndex(){','function moonlightAssetAge(){'),ctx);
vm.runInContext(block('function evaluateChuseokFestival(){','function moonlightEntrantImage('),ctx);
vm.runInContext('const moonlightStoryBeats=["opening"];',ctx);
const result=ctx.evaluateChuseokFestival();assert.equal(result.technical,200);assert.equal(result.artistic,200);assert.equal(result.player.score,200);assert.equal(result.ranked.length,8);
ctx.game.agility=400;assert.ok(ctx.evaluateChuseokFestival().technical>result.technical);
vm.runInContext(block('const sehwaContestants=[','const sehwaStoryBeats='),ctx);
vm.runInContext(block('function sehwaAgeIndex(){','function sehwaAssetAge(){'),ctx);
vm.runInContext(block('function evaluateSeollalFestival(){','function sehwaOpeningAnswer('),ctx);
assert.equal(ctx.evaluateSeollalFestival().player.score,200);
ctx.game.charm=900;assert.equal(ctx.evaluateSeollalFestival().player.score,200,'art quality does not depend on appearance');
ctx.game.sensitivity=400;assert.equal(ctx.evaluateSeollalFestival().player.score,320);
const render=block('function renderSehwaContest(','function waitForSehwaAdvance(');
assert.match(render,/sehwaSubmissionCard/);assert.doesNotMatch(render,/preparationSceneBackground|sehwaPreparationEnsemble/);
assert.match(app,/return waitForFestivalTapAdvance/);
console.log('PASS: deleted jobs, idempotent save migration, art quality, dance scoring, submission-only stage');
