import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';

const html=readFileSync(new URL('../src/index.html',import.meta.url),'utf8');
const css=readFileSync(new URL('../src/style.css',import.meta.url),'utf8');
const schedule=readFileSync(new URL('../src/schedule.css',import.meta.url),'utf8');
const app=readFileSync(new URL('../src/app.js',import.meta.url),'utf8');

const outside=html.indexOf('class="background home-outside"');
const weather=html.indexOf('class="home-weather"');
const room=html.indexOf('class="home-room-foreground"');
assert.ok(outside>=0&&outside<weather&&weather<room,'home layers must be outside → weather → room/frame');
assert.match(css,/\.home-outside\{z-index:0/,'outside layer must be behind weather');
assert.match(css,/\.home-weather\{position:absolute;z-index:1/,'weather must be between outside and room');
assert.match(css,/\.home-room-foreground\{position:absolute;z-index:2/,'room/frame must be in front');
for(const layer of ['home-outside','home-weather','home-room-foreground'])assert.ok(css.includes(`.phone.playing>.${layer}`),`${layer} must be hidden during schedules`);
for(const mode of ['market-playing','vacation-playing'])for(const layer of ['home-outside','home-weather','home-room-foreground'])assert.ok(css.includes(`.phone.${mode}>.${layer}`),`${layer} must be hidden during ${mode}`);
assert.ok(html.includes('class="activity-backdrop"'),'schedules need a separate full-screen activity backdrop');
assert.match(css,/\.phone\.playing:not\(\.market-playing\):not\(\.vacation-playing\)>\.activity-backdrop\{display:block\}/,'full activity backdrop must remain visible behind the RPG window');
assert.match(schedule,/action-holiday-seollal\{inset:0!important;[^}]*overflow:hidden!important\}/,'Seollal stage must fill the phone without an extra border');
assert.match(schedule,/animation:sehwa-brush-frame-10fps 1s steps\(1,end\) infinite/,'one complete solo frame must run at a time at 10fps without stacking a second brush');
assert.doesNotMatch(schedule,/\.sehwa-hero\.is-brush-frames\{[^}]*transform:/,'brush-frame motion must not shake the whole character/table layer');
assert.match(app,/className='festival-tap-next'/,'a visible next-scene button must appear when the minimum scene time ends');
assert.match(app,/fallStart=7,fallEnd=15/,'childcare falls must hold before recovering instead of snapping upright');
assert.match(schedule,/action-holiday-seollal:not\(\[hidden\]\)\) \.activity-playback\{top:7%!important/,'Seollal speed control must align with the dialogue upper-right edge');
assert.match(schedule,/action-holiday-seollal:not\(\[hidden\]\)\)>\.settings-gear\{top:7%!important/,'Seollal settings control must align with the dialogue upper-right edge');
assert.match(app,/preparationSceneBackground=`\.\.\/assets\/events\/holidays\/sehwa-contest\/preparation-scene\/eight-entrant-v1\/drawing-1-mobile-3x5-v1\.png/, 'the complete 3:5 preparation scene must become the stage background');
assert.ok(existsSync(new URL('../assets/events/holidays/sehwa-contest/preparation-scene/eight-entrant-v1/drawing-1-mobile-3x5-v1.png',import.meta.url)),'the seamless 3:5 preparation image must be committed with the game');
assert.match(app,/preparing\?preparationSceneBackground:emptySceneBackground/, 'the 8-person base frame must replace the empty hall only in the preparation scene');
assert.doesNotMatch(app,/class="sehwa-ensemble-base"/, 'the stable base frame must not be composited above a second hall background');
assert.match(app,/drawing-1-mobile-3x5-hands-v1\.png/,'the preparation scene must use a same-ratio hand-motion frame above the single background');
assert.match(app,/hands\.map\(\(\[x,y,dx,dy\],index\)=>`<img class="sehwa-ensemble-motion-patch"/,'the preparation scene must animate individual localized hand patches above the single background');
assert.match(schedule,/\.sehwa-eight-entrant-scene \.sehwa-ensemble-motion-patch\{[\s\S]*mask-image:var\(--sehwa-hand-mask\)[\s\S]*sehwa-eight-hand-stroke 3\.2s ease-in-out/,'each entrant patch must be limited to a small, readable brush-hand area');
assert.match(schedule,/\.sehwa-eight-entrant-scene \.sehwa-ensemble-motion-patch\{inset:0!important;[^}]*object-fit:cover!important/,'the 3:5 hand-motion overlay must not be shrunk by the retired 2:3 contain rule');
console.log('PASS: home layer order, schedule isolation, Seollal border and motion contracts');
