import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {existsSync} from 'node:fs';
const app=readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const css=readFileSync(new URL('../src/schedule.css',import.meta.url),'utf8');
assert.match(app,/function waitForSehwaAdvance\(beat\)/,'설날 장면은 전용 진행 대기가 필요합니다.');
assert.match(app,/minimumStay=beat===5\?5000:beat<=1\?1600:700/,'그림 시작은 5초, 시작 대화는 1.6초 이상 보여야 합니다.');
assert.match(app,/await waitForSehwaAdvance\(beat\)/,'설날 장면은 다음 버튼 입력을 기다려야 합니다.');
assert.match(app,/function sehwaOpeningAnswer\(session\)/,'스테이터스에 따른 선화의 시작 답변이 필요합니다.');
assert.match(app,/function sehwaOpeningDialogue\(session,beat\)/,'시작과 동시에 신수 응원 대화가 필요합니다.');
assert.match(app,/speaker-\$\{guardianTurn\?'guardian':'seonhwa'\}/,'신수와 선화가 번갈아 말하는 화자 구분이 필요합니다.');
assert.doesNotMatch(app,/class="pageant-beat"/,'명절 이벤트 내부에는 중복되는 하단 설명창이 없어야 합니다.');
assert.doesNotMatch(app,/overlay\.innerHTML=`\$\{opening\?'':festivalCrowd\(\)\}/,'설날 이벤트에는 관객 실루엣을 렌더링하지 않아야 합니다.');
assert.match(app,/const guardian=guardianResult\?festivalGuardianCut\(session\):''/,'마음을 다잡는 3장면에는 신수가 다시 나타나지 않아야 합니다.');
assert.match(css,/\.activity-stage:has\(\.moonlight-pageant:not\(\[hidden\]\)\) \.stage-pm3-hud>#stageHudStats\{display:none!important\}/,'명절 이벤트 전체 장면에는 스테이터스 막대가 없어야 합니다.');
assert.match(css,/@keyframes sehwa-dialogue-from-right/,'신수 대화창의 오른쪽 슬라이드가 필요합니다.');
assert.match(css,/@keyframes sehwa-dialogue-from-left/,'선화 대화창의 왼쪽 슬라이드가 필요합니다.');
assert.match(css,/\.sehwa-opening-dialogue p\{[^}]*word-break:keep-all;[^}]*text-wrap:pretty/,'한글 대사는 어절 중간에서 끊기지 않아야 합니다.');
assert.match(app,/protagonistFullbodyForAge\(\)/,'선화 대화는 연령별 상반신 원화를 사용해야 합니다.');
assert.match(app,/drawing-\$\{frame\}-v2\.png/,'세화 붓질 장면의 선화는 연령별 반실사 v2 프레임을 사용해야 합니다.');
assert.match(css,/\.sehwa-opening-dialogue>\.sehwa-dialogue-bust\{[^}]*transform:scale\(1\.28\)/,'대화 중 화자는 통일된 얼굴·상체 크기로 보여야 합니다.');
assert.match(app,/function sehwaExpressionAsset\(expression\)/,'연령별 투명 표정 자산을 선택해야 합니다.');
for(const age of ['09','13','16','18'])for(const expression of ['neutral','smile','joyful','nervous','startled','sad','determined','shy'])assert.ok(existsSync(new URL(`../assets/characters/dialogue-busts/seonhwa/age-${age}-${expression}-v2.png`,import.meta.url)),`${age}세 ${expression} 투명 대화 표정이 필요합니다.`);
assert.doesNotMatch(app,/function sehwaDrawingEnsemble\(session\)/,'공중에 뜬 8인 판자 합성 장면이 남아 있으면 안 됩니다.');
assert.match(app,/preparing=beat===4,drawing=beat>=5&&beat<=10/,'화구 준비 다음에는 선화의 정상 붓질 동작으로 바로 이어져야 합니다.');
assert.match(app,/function sehwaPreparationEnsemble\(session\)/,'빈 준비 장면 대신 참가자 8명의 화구 준비 장면이 필요합니다.');
assert.match(app,/\$\{preparing\?sehwaPreparationEnsemble\(session\):''\}/,'참가자와 책상은 준비 장면에서만 보여야 합니다.');
assert.doesNotMatch(app,/title\|\|preparing\?sehwaPreparationEnsemble/,'제목 장면에는 참가자와 책상이 다시 나타나면 안 됩니다.');
assert.match(app,/책상에서 그림을 그리는 쯔꾸르 참가자 8명/,'준비 장면에는 좌우 네 명씩 여덟 참가자가 필요합니다.');
assert.match(app,/eight-entrant-v1/,'8인 그림 그리기 전용 장면을 사용해야 합니다.');
assert.ok(existsSync(new URL('../assets/events/holidays/sehwa-contest/preparation-scene/eight-entrant-v1/drawing-1.png',import.meta.url)),'8인 그림 장면이 필요합니다.');
assert.match(app,/\{id:'eunseo',name:'은서'/,'플레이어를 포함한 8인 참가 명단이 필요합니다.');
assert.match(app,/8인 세화 심사/,'설날 심사표도 8인 기준이어야 합니다.');
for(const frame of [1,2,3,4,5,6])assert.ok(existsSync(new URL(`../assets/events/holidays/sehwa-contest/preparation-scene/age-13/preparation-${frame}.png`,import.meta.url)),`13세 화구 준비 ${frame} 프레임이 필요합니다.`);
for(let frame=1;frame<=12;frame+=1)assert.ok(existsSync(new URL(`../assets/events/holidays/sehwa-contest/preparation-scene/age-13/smooth-${String(frame).padStart(2,'0')}.png`,import.meta.url)),`13세 부드러운 화구 준비 ${frame} 프레임이 필요합니다.`);
assert.match(css,/animation:sehwa-preparation-frames 7\.2s/,'참가자별 비동기 준비 동작은 12프레임으로 부드럽게 순환해야 합니다.');
assert.match(css,/\.sehwa-drawing-ensemble\.is-preparing figure:nth-child\(-n\+4\)\{[^}]*scale\(\.82\)/,'준비 장면의 뒤쪽 참가자는 원근에 맞게 작아야 합니다.');
assert.match(css,/\.sehwa-drawing-ensemble\.is-preparing i:before,[^{]+\{[^}]*height:23px/,'준비 장면 책상에는 떠 보이지 않도록 다리가 있어야 합니다.');
assert.doesNotMatch(app,/function sehwaRegistrationScene\(\)/,'삭제한 참가 접수 장면이 남아 있으면 안 됩니다.');
assert.doesNotMatch(app,/royal-contest-registration-young-clerk-v2\.png/,'설날 경연 중 접수 배경으로 바뀌면 안 됩니다.');
assert.doesNotMatch(app,/class="sehwa-registration-clerk"/,'접수 장면에 이질적인 별도 합성 NPC가 남아 있으면 안 됩니다.');
assert.doesNotMatch(app,/npcs\/shops\/hanbok-owner\.png[^\n]*왕실 화원 접수/,'한복점 주인 자산을 왕실 접수 NPC로 재사용하면 안 됩니다.');
assert.doesNotMatch(app,/study-child-tsukuru-v1\.png[^\n]*왕실 화원 접수/,'체커보드 배경이 남은 접수 NPC 자산을 사용하면 안 됩니다.');
assert.doesNotMatch(app,/teacher-reading-1\.png[^\n]*왕실 화원 접수/,'세화 접수 장면에 노년 선생 자산이 남아 있으면 안 됩니다.');
assert.match(css,/\.sehwa-contest\.festival-pm3\{overflow:visible\}/,'창 밖 진행 버튼을 위해 세화 오버레이가 열려 있어야 합니다.');
assert.match(css,/\.activity-stage:not\(\.market-choice-stage\):has\(\.sehwa-contest:not\(\[hidden\]\)\)>\.stage-inner\{overflow:visible!important\}/,'쯔꾸르 창 바깥 버튼이 stage-inner에 잘리면 안 됩니다.');
assert.doesNotMatch(app,/<button class="pageant-next"/,'설날 경연에 별도 다음 버튼이 남아 있으면 안 됩니다.');
assert.match(app,/return waitForFestivalTapAdvance\(minimumStay\)/,'설날 경연은 화면 터치로 진행해야 합니다.');
for(const frame of [1,2,3])assert.ok(existsSync(new URL(`../assets/events/holidays/sehwa-contest/registration-scene/age-13/receive-${frame}-v1.png`,import.meta.url)),`공손한 참가표 수령 ${frame} 프레임이 필요합니다.`);
assert.ok(existsSync(new URL('../assets/events/holidays/sehwa-contest/background/royal-contest-registration-young-clerk-v2.png',import.meta.url)),'축소된 접수대가 포함된 왕실 화원 접수 배경 이미지가 필요합니다.');
assert.match(css,/@keyframes sehwa-receive-bow/,'참가표 수령은 공손한 인사로 시작해야 합니다.');
assert.match(css,/@keyframes sehwa-receive-reach/,'참가표 수령은 두 손을 내미는 자세로 이어져야 합니다.');
assert.match(css,/@keyframes sehwa-receive-hold/,'참가표 수령은 표를 받은 자세로 끝나야 합니다.');
assert.doesNotMatch(css,/sehwa-(?:receive|slip)[^;}]*infinite/,'참가표 수령 동작은 반복되면 안 됩니다.');
assert.match(css,/@keyframes sehwa-slip-handover/,'참가표가 접수 관리에게서 선화에게 이동해야 합니다.');
assert.match(app,/선화가 자리에 앉아 세화를 그리기 시작했어요/,'구형 8인 판자 장면 대신 선화의 그림 시작 서술이 필요합니다.');
assert.match(css,/\.sehwa-drawing-ensemble\{[^}]*grid-template-columns:repeat\(4,1fr\)/,'참가자 8명은 4×2 구도로 배치해야 합니다.');
assert.match(css,/\.sehwa-contest\.festival-pm3 \.sehwa-hero\{[^}]*width:210px!important;[^}]*height:270px!important/,'설날 반실사 주인공은 중앙에서 충분히 크게 보여야 합니다.');
console.log('PASS: 설날 수동 진행·5초 전원 그림·스테이터스 응답·캐릭터 축소·공손한 참가표 수령');
