import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..');
const app=fs.readFileSync(path.join(root,'src/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'src/schedule.css'),'utf8');
const html=fs.readFileSync(path.join(root,'src/index.html'),'utf8');
const shownVersion=html.match(/loading-version[^>]*>v([^<]+)/)?.[1];
for(const asset of ['app.js','style.css','schedule.css'])assert.ok(shownVersion&&html.includes(`${asset}?v=${shownVersion}`),`${asset} cache key`);
const contestantBlock=app.match(/const moonlightContestants=\[([\s\S]*?)\n\];/)?.[1]||'';
assert.equal((contestantBlock.match(/scores:\[/g)||[]).length,7,'선화 포함 참가자 8명');
const beats=app.match(/const moonlightStoryBeats=\[([\s\S]*?)\n\];/)?.[1]||'';
assert.equal((beats.match(/'[^']+'/g)||[]).length,8,'사용자가 확정한 8단계');
for(const phrase of ['신수와 선화','무대 중앙','팔과 손목, 손끝','왕과 심사관','여덟 참가자','상을 수여','반실사','능력치와 보상'])assert.ok(beats.includes(phrase),phrase);
assert.match(app,/moonlightMotionNames=\['opening-dialogue','stage-enter','dance','royal-judging','ranking','award','winner-acceptance','guardian-congratulation'\]/,'8단계 모션 순서');
assert.match(app,/function moonlightPreparationDialogue\(session\)/,'시작 장면의 신수·선화 대화');
assert.match(app,/moonlightPreparationDialogue\(session\):entrance\?moonlightOpeningDialogue\(session,1\)/,'첫 장면에서 응원과 답변을 함께 렌더링');
assert.match(app,/consistent-dance-v9\/seonhwa-dance-slow-v1\.png/,'잘리지 않은 동일 선화 전신 춤 자산만 사용');
assert.match(css,/moonlight-complete-dance 5\.6s/,'느린 손끝 춤');
assert.match(css,/pageant-hero-frames\.is-dance\{[^}]*left:50%!important/,'중앙 춤');
for(const age of ['09','13','16','19'])assert.ok(fs.existsSync(path.join(root,`assets/characters/seonhwa/identity-semi-real-v9/seonhwa-age${age}-identity-v9.png`)),`선화 ${age}세 반실사 기준 초상`);
assert.ok(fs.existsSync(path.join(root,'assets/events/holidays/moonlight-pageant/seonhwa/consistent-dance-v9/seonhwa-dance-slow-v1.png')),'complete dance');
assert.match(app,/const guardianType=game\.guardianType\|\|'hyeonmu';/,'신수 미선택 상태에도 도입 대화 유지');
assert.match(css,/motion-royal-judging \.festival-character-cut\.king-cut p[\s\S]*bottom:4%!important/,'왕의 얼굴과 대화창 분리');
assert.match(app,/const portrait=playerWinner[\s\S]*baseSpriteForAge\(\)[\s\S]*moonlightEntrantImage\(winner\)/,'우승자별 나이 맞춤 반실사 수상 소감 분기');
assert.match(app,/festivalScoreboard\(session,'참가자 8명 최종 순위와 수상 결과'\)/,'8명 순위 발표');
assert.match(app,/festivalKingWinnerCongratulations\(session\)/,'왕 시상·축하');
assert.match(app,/festivalGuardianCut\(session\)/,'신수 마지막 축하');
console.log('PASS: 한가위 8단계, 동일 선화 중앙 전신 춤, 왕 시상, 우승자 반실사 소감, 신수 마무리');
