import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const html=readFileSync(new URL('../src/index.html',import.meta.url),'utf8');
const css=readFileSync(new URL('../src/style.css',import.meta.url),'utf8');
const schedule=readFileSync(new URL('../src/schedule.css',import.meta.url),'utf8');
const app=readFileSync(new URL('../src/app.js',import.meta.url),'utf8');

const outside=html.indexOf('class="background home-outside"');
const weather=html.indexOf('class="home-weather"');
const room=html.indexOf('class="home-room-foreground"');
assert.ok(outside>=0&&outside<weather&&weather<room,'home layers must be outside → weather → room/frame');
assert.match(css,/\.home-outside\{z-index:0/,'outside layer must be behind weather');
assert.match(css,/\.home-weather\{position:absolute;z-index:1/,'weather must be between outside and room');
assert.match(css,/\.home-room-foreground\{position:absolute;z-index:2/,'room/frame must be in front');
for(const layer of ['home-outside','home-weather','home-room-foreground'])assert.ok(css.includes(`.phone.playing>.${layer}`),`${layer} must be hidden during schedules`);
for(const mode of ['market-playing','vacation-playing'])for(const layer of ['home-outside','home-weather','home-room-foreground'])assert.ok(css.includes(`.phone.${mode}>.${layer}`),`${layer} must be hidden during ${mode}`);
assert.ok(html.includes('class="activity-backdrop"'),'schedules need a separate full-screen activity backdrop');
assert.match(css,/\.phone\.playing:not\(\.market-playing\):not\(\.vacation-playing\)>\.activity-backdrop\{display:block\}/,'full activity backdrop must remain visible behind the RPG window');
assert.match(schedule,/action-holiday-seollal\{inset:0!important;[^}]*overflow:hidden!important\}/,'Seollal stage must fill the phone without an extra border');
assert.match(schedule,/\.sehwa-eight-entrant-scene \.sehwa-ensemble-base\{[^}]*opacity:1/,'the hall, floor and desks must remain a static base frame');
assert.match(schedule,/\.sehwa-eight-entrant-scene \.sehwa-ensemble-motion-patch\{[\s\S]*mask-image:[^;]+[\s\S]*animation:sehwa-eight-local-painting/,'only feathered regions around the eight painters may change pose');
assert.match(schedule,/animation:sehwa-brush-frame-10fps 1s steps\(1,end\) 5/,'ten transparent solo frames must run at 10fps for five seconds');
assert.doesNotMatch(schedule,/\.sehwa-hero\.is-brush-frames\{[^}]*transform:/,'brush-frame motion must not shake the whole character/table layer');
assert.match(app,/className='festival-tap-next'/,'a visible next-scene button must appear when the minimum scene time ends');
assert.match(app,/fallStart=7,fallEnd=15/,'childcare falls must hold before recovering instead of snapping upright');
assert.match(schedule,/action-holiday-seollal:not\(\[hidden\]\)\) \.activity-playback\{top:7%!important/,'Seollal speed control must align with the dialogue upper-right edge');
assert.match(schedule,/action-holiday-seollal:not\(\[hidden\]\)\)>\.settings-gear\{top:7%!important/,'Seollal settings control must align with the dialogue upper-right edge');
assert.match(app,/class="sehwa-ensemble-base"[^>]+drawing-1-v2/,'the approved stable base frame must be rendered');
assert.match(app,/\[2,3\]\.map\(\(frame,index\)=>`<img class="sehwa-ensemble-motion-patch"/,'only two localized motion patches may be composited above the base');
assert.match(schedule,/\.sehwa-eight-entrant-scene img\{[^}]*object-fit:contain/,'all eight contestants must fit inside the scene without edge cropping');
assert.match(schedule,/\.sehwa-eight-entrant-scene \.sehwa-ensemble-base\{[\s\S]*mask-image:linear-gradient\(to bottom,transparent/,'the contained ensemble must feather into the hall without a rectangular seam');
console.log('PASS: home layer order, schedule isolation, Seollal border and motion contracts');
